name: Build ANGEL A.C Scanner EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole angel_scanner.py --name angel-scanner

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: angel-scanner
          path: dist/angel-scanner.exe
